FROM python:3.10-slim

# 필수 패키지 및 Chrome 의존성 설치
RUN apt-get update && apt-get install -y \
    wget unzip curl gnupg2 \
    libnss3 libgconf-2-4 libxi6 libxcursor1 libxcomposite1 \
    libasound2 libxtst6 libxrandr2 libatk-bridge2.0-0 libgtk-3-0 \
    libx11-xcb1 libdbus-glib-1-2 fonts-liberation ca-certificates \
    libgbm1 libxshmfence1 libegl1 \
    --no-install-recommends && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Chrome & Chromedriver 버전
ENV CHROME_VERSION=138.0.7204.183

# Chrome 설치
#RUN mkdir -p /opt/chrome && \
#    wget -q https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chrome-linux64.zip && \
#    unzip chrome-linux64.zip && \
#    mv chrome-linux64/* /opt/chrome/ && \
#    rm -rf chrome-linux64.zip chrome-linux64

# Chrome-Headless-Shell 설치
# 부하로 인해 headless 버전으로 변경
RUN mkdir -p /opt/chrome && \
    wget -q https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chrome-headless-shell-linux64.zip && \
    unzip chrome-headless-shell-linux64.zip && \
    mv chrome-headless-shell-linux64/* /opt/chrome/ && \
    rm -rf chrome-headless-shell-linux64.zip chrome-headless-shell-linux64

# ChromeDriver 설치
RUN wget -q https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chromedriver-linux64.zip && \
    unzip chromedriver-linux64.zip && \
    mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver && \
    chmod +x /usr/local/bin/chromedriver && \
    rm -rf chromedriver-linux64.zip chromedriver-linux64

# 환경변수 설정
ENV PATH="/opt/chrome:$PATH"
ENV CHROME_BIN="/opt/chrome/chrome"

# 버전 출력 (빌드시 로그용)
#RUN /opt/chrome/chrome --version && chromedriver --version
RUN /opt/chrome/chrome-headless-shell --version && chromedriver --version

# 파이썬 패키지 설치
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 앱 복사 및 작업 디렉토리 설정
COPY . /app
WORKDIR /app
RUN mkdir -p log

CMD ["python", "selenium_news_crawler.py"]
