# config.ini
[database]
host = 127.0.0.1
port = 3306
user = appuser
password = appuserpass
db_name = crawler_sentiment_analysis 
charset = utf8mb4

[elasticsearch]
host = 127.0.0.1
port = 9200
scheme = http
source_index = dataset_articles

[embedding_model]
api_key = ollama
; ollama local
base_url = http://localhost:11434/v1
model = qllama/bge-m3:q4_k_m

; Colab cloudflare
;base_url = https://ata-fact-mins-secret.trycloudflare.com/v1
;model = bge-m3

[llm_model]
; Colab cloudflare
api_key = ollama
base_url = https://camera-activists-navigate-coaching.trycloudflare.com/v1 
model = Qwen3-4B-Instruct

[embedder_settings]
concurrency = 3
fetch_size = 5000
rate_limit_delay = 0.2
commit_interval= 100

[labeler_settings]
concurrency = 8
fetch_size = 5000
rate_limit_delay = 0.2
commit_interval= 100

[summarizer_settings]
concurrency = 8
fetch_size = 5000
