# config.ini
[mysql]
host = 127.0.0.1
port = 3306
user = appuser
password = appuserpass
database = crawler_sentiment_analysis 
charset = utf8mb4

[elasticsearch]
host = 127.0.0.1
port = 9200
scheme = http
source_index = dataset_articles


[llm]
; LLM API 설정
api_key = ollama
; Colab 
;base_url = https://unconstruable-nonfactually-cedric.ngrok-free.dev/v1
;model = Qwen3-4B-Instruct

; Docker Model Runner
;base_url=http://localhost:12434/engines/llama.cpp/v1
;model = ai/qwen3:4B-UD-Q4_K_XL
;model=huggingface.co/lmstudio-community/qwen3-4b-instruct-2507-gguf:q4_k_m

; ollama (docker)
base_url=http://localhost:11434/v1
model=qwen3:4b-instruct-2507-q4_K_M

[llm_async]
; LLM API 설정
api_key = ollama
; Colab ngrok
;base_url = https://unconstruable-nonfactually-cedric.ngrok-free.dev/v1
;model = Qwen3-4B-Instruct

; Colab cloudflare
base_url = https://fast-around-restaurants-relay.trycloudflare.com/v1 
model = Qwen3-4B-Instruct

;AWS EC2 VM
;base_url=http://3.38.247.93:8000/v1
;model=Qwen3-4B-Instruct


# [추가] 비동기 배치 및 속도 제한 설정
[async]
concurrency = 8
# 한 번에 DB에서 가져올 기사 수
fetch_size = 1000

# - 비동기 배치이므로 사용 안함 -
# rate_limit_delay = 0.2
# commit_interval= 100 
